// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Renderer")>]
[<assembly: AssemblyProductAttribute("electron-fable-mwe")>]
[<assembly: AssemblyDescriptionAttribute("Close to minimum framework for electron fable3 using elmish")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Renderer.Tests")>]
do ()
